[project]
name = "lol-blender"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fake-bpy-module-4-2>=20250130",
    "numpy>=1.24.4",
    "rust-wrap",
]

[tool.uv.sources]
rust-wrap = { path = "addon/wheels/rust_wrap-0.1.0-cp311-abi3-linux_x86_64.whl" }
