name: Release on Merge To Master
on:
  push:
    branches:
      - gh-actions
jobs:

  release-addon:
    needs: [bindings-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Bundle Add-on
        run: python release.py --no-zip
      - id: release
        uses: dctrotz/release-on-push-action@fixupload_url
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: minor
      - name: Patch Add-on Version
        run: python release.py --tag ${{steps.release.outputs.version}}
      - name: Zip Add-on
        run: python release.py --zip-only lol-blender-${{steps.release.outputs.tag_name}}
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: dist/lol-blender-${{steps.release.outputs.tag_name}}.zip
          asset_name: lol-blender-${{steps.release.outputs.tag_name}}.zip
          asset_content_type: application/zip

  bindings-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, i686]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: x64
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          manylinux: auto
          args: --release --out dist/ -m bindings/Cargo.toml
      - name: Upload wheels
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["./dist/*.whl"]'
permissions:
  contents: write
  pull-requests: read